### ISSUE TITLE
demo 里的echo json 返回无法被前端正确识别

### ISSUE THREAD

**Issue by yangweijie** [misscx/api-doc#1]
tp 5 6 默认输出 早就改为return了  
![image](https://user-images.githubusercontent.com/1614114/89618109-11aa9800-d8be-11ea-97b3-8a38e5a2c7b4.png)
![image](https://user-images.githubusercontent.com/1614114/89618115-14a58880-d8be-11ea-9c9d-28178348446e.png)

改为 return json 函数后正常输出和格式化
![image](https://user-images.githubusercontent.com/1614114/89618172-30a92a00-d8be-11ea-8bd5-c65a10abe64d.png)

**Comment by misscx** [comment]
> tp 5 6 默认输出 早就改为return了
> ![image](https://user-images.githubusercontent.com/1614114/89618109-11aa9800-d8be-11ea-97b3-8a38e5a2c7b4.png)
> ![image](https://user-images.githubusercontent.com/1614114/89618115-14a58880-d8be-11ea-9c9d-28178348446e.png)
> 
> 改为 return json 函数后正常输出和格式化
> ![image](https://user-images.githubusercontent.com/1614114/89618172-30a92a00-d8be-11ea-8bd5-c65a10abe64d.png)

没注意这TP的变化，貌似我用echo好像也可以使用，但还是改过来用return了。
